config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :conversations, only: [:index, :new, :create] do
    resources :messages, only: [:index, :create] do
      post :mark_read, on: :member
    end
  end
  
  resources :users, only: [] do
    get :autocomplete_user_email, on: :collection
  end
  
  resources :messages, only: [] do
    get :unread, on: :collection, format: :json
  end
  
  root to: 'default#show'
end

app/models/conversation.rb
# == Schema Information
#
# Table name: conversations
#
#  id             :integer          not null, primary key
#  first_user_id  :integer
#  second_user_id :integer
#

class Conversation < ApplicationRecord
  belongs_to :first_user, class_name: 'User'
  belongs_to :second_user, class_name: 'User'
  has_many :messages, inverse_of: :conversation
  
  validates :first_user_id, :second_user_id, presence: true
  validate :validate_companion
  
  def self.for_users(first_user, second_user)
    first_user_id, second_user_id = first_user.try(:id), second_user.try(:id)
    direct_condition = { first_user_id: first_user_id, second_user_id: second_user_id }
    reversed_condition = { first_user_id: second_user_id, second_user_id: first_user_id }
    where(direct_condition).or(where(reversed_condition)).first or create(direct_condition)
  end
  
  def self.for_user(user)
    where(first_user_id: user.id).or(where(second_user_id: user.id))
  end

  def companion(user)
    second_user == user ? first_user : second_user
  end
  
  def validate_companion
    if first_user_id == second_user_id
      errors.add(:second_user, 'You cannot write to yourself')
      self.second_user = nil
    end
  end
  
  def new_messages_count(user)
    messages.where(is_read: false, receiver_id: user.try(:id)).count
  end
end

app/controllers/conversations_controller.rb
class ConversationsController < ApplicationController
  include ConversationsHelper

  before_action :authenticate_user!

  def index
    @conversations = load_conversations
    respond_to do |format|
      format.html { @new_messages = current_user.incoming_messages.unread }
      format.json { render json: conversations_list_react_params(@conversations) }
    end
  end
  
  def new
    @conversation = Conversation.new
  end
  
  def create
    second_user = User.find(params[:conversation][:second_user_id]) rescue nil
    @conversation = Conversation.for_users(current_user, second_user)
    
    if @conversation.persisted?
      redirect_to conversation_messages_path(@conversation)
    else
      render :new
    end
  end
  
  private
  
  def load_conversations
    current_user.conversations.includes(:first_user, :second_user).offset(params[:offset].to_i).order(updated_at: :desc).limit(10)
  end
end

app/helpers/conversations_helper.rb
module ConversationsHelper
  def conversations_list_react_params(conversations)
    { conversations: conversations.map do |conversation|
      { id: conversation.id,
        messages_url: conversation_messages_path(conversation),
        new_messages_count: conversation.new_messages_count(current_user),
        user_email: conversation.companion(current_user).email }
    end,
      load_more_path: conversations_path(offset: params[:offset].to_i + conversations.size, format: :json),
      total_count: current_user.conversations.count
    }.deep_transform_keys! { |c| c.to_s.camelcase(:lower).to_sym }
  end
end

app/views/conversations/_form.html.slim
.form-group
  = simple_form_for(@conversation) do |f|
    = f.error_notification
    = f.input :second_user, hint: 'Start typing email', as: :autocomplete, source_query: autocomplete_user_email_users_path
    = f.submit 'Start'

app/views/conversations/index.html.slim
.row
  .col-sm-8
    .panel.panel-default
      .panel-heading
        h4 = t('New messages')
        .panel-body
          == react_component('MessagesPanel', messages_react_params(@new_messages, recent: true))

  .col-sm-4
    .panel.panel-default
      .panel-heading
        h4 = t('Conversations')
      .panel-body
        .btn-group
          a.btn.btn-default href=new_conversation_path = t('Start new conversation')
        == react_component('ConversationsList', conversations_list_react_params(@conversations))

app/views/conversations/new.html.slim
.panel.panel-default
  .panel-heading
    h5 = t('New conversation')
  .panel-body
    == render 'conversations/form'